job:
  image: golang:1.12.7-stretch

  variables:
    GO111MODULE: "on"

  script:
    #Fetch master to be used in deploy condition to prevent deploying on old commits.
    - whoami && pwd
    - USER=$(whoami)
    - ./e2e/e2e.sh

  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - $HOME/.cache/go-build
      - $HOME/gopath/pkg/mod

  before_script:
    - whoami && pwd
    - USER=$(whoami)
    - apt update -q && apt install -qqy --no-install-recommends locales-all sudo youtube-dl ffmpeg tree curl
    - apt install -qqy --no-install-recommends python-pip python-dev libffi-dev libssl-dev gcc libc-dev make
    - curl -fsSL https://get.docker.com -o get-docker.sh
    - sudo sh get-docker.sh
    - sudo usermod -aG docker $USER
    - sudo curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
