package tagsManager

import (
	"regexp"
	"sort"
	"strings"

	log "github.com/sirupsen/logrus"
)

const (
	Gaming     = "gaming"
	Blockchain = "blockchain"
	News       = "news"
	Learning   = "learning"
	Funny      = "funny"
	Technology = "technology"
	Automotive = "automotive"
	Economics  = "economics"
	Sports     = "sports"
	Food       = "food"
	Science    = "science"
	Art        = "art"
	Nature     = "nature"
	Beliefs    = "beliefs"
	Music      = "music"
	PopCulture = "pop culture"
	Weapons    = "weapons"
)

func GetTagsForChannel(channelID string) []string {
	tags, _ := channelWideTags[channelID]
	return tags
}

func SanitizeTags(tags []string, youtubeChannelID string) ([]string, error) {
	unsanitized := make([]string, 0, len(tags))
	for _, t := range tags {
		t, err := normalizeTag(t)
		if err != nil {
			return nil, err
		}
		if t == "" {
			continue
		}
		unsanitized = append(unsanitized, t)
	}
	ts := &tagsSanitizer{
		Unsanitized: unsanitized,
		ChannelID:   youtubeChannelID,
	}
	ts.init()
	ts.cleanup()
	ts.replace()
	ts.add()

	originalTags := make([]string, 0, len(ts.Sanitized))
	curatedTags := make([]string, 0, len(ts.Sanitized))
	for t, curated := range ts.Sanitized {
		if curated {
			curatedTags = append(curatedTags, t)
		} else {
			originalTags = append(originalTags, t)
		}
	}
	sanitizedTags := make([]string, 0, len(originalTags)+len(curatedTags))
	sort.Strings(curatedTags)
	sort.Strings(originalTags)
	sanitizedTags = append(sanitizedTags, curatedTags...)
	sanitizedTags = append(sanitizedTags, originalTags...)
	return sanitizedTags, nil
}

func normalizeTag(t string) (string, error) {
	t = strings.ToLower(t)
	multipleSpaces := regexp.MustCompile(`\s{2,}`)
	leadingAndTrailingSpaces := regexp.MustCompile(`^\s+|\s$`)
	hashTags := regexp.MustCompile(`(#\d+\s)|#+`)
	inParenthesis := regexp.MustCompile(`\([^\)]+\)`)
	weirdChars := regexp.MustCompile(`[^-\w'& +\/A-Za-zÀ-ÖØ-öø-ÿ]`)
	startsOrEndsInWeirdChars := regexp.MustCompile(`^[^A-Za-zÀ-ÖØ-öø-ÿ0-9]+|[^A-Za-zÀ-ÖØ-öø-ÿ0-9]+$`)
	t = hashTags.ReplaceAllString(t, "")
	t = inParenthesis.ReplaceAllString(t, " ")
	t = startsOrEndsInWeirdChars.ReplaceAllString(t, "")
	t = multipleSpaces.ReplaceAllString(t, " ")
	t = leadingAndTrailingSpaces.ReplaceAllString(t, "")
	if weirdChars.MatchString(t) {
		log.Debugf("tag '%s' has weird stuff in it, skipping\n", t)
		return "", nil

	}
	return t, nil
}

type tagsSanitizer struct {
	Unsanitized []string
	Sanitized   map[string]bool
	ChannelID   string
}

func (ts *tagsSanitizer) init() {
	if len(ts.Sanitized) == 0 {
		ts.Sanitized = make(map[string]bool, len(ts.Unsanitized)+16)
	}
}

func (ts *tagsSanitizer) cleanup() {
	for _, t := range ts.Unsanitized {
		_, ok := tagsToSkip[t]
		if !ok {
			ts.Sanitized[t] = false
		}
	}
}

func (ts *tagsSanitizer) replace() {
	for _, t := range ts.Unsanitized {
		match, filterMatch := mapAndReplace[t]
		if filterMatch {
			delete(ts.Sanitized, t)
			ts.Sanitized[match] = true
		}
	}
}

func (ts *tagsSanitizer) add() {
	for _, t := range ts.Unsanitized {
		match, filterMatch := mapAndKeep[t]
		if filterMatch {
			ts.Sanitized[match] = true
			ts.Sanitized[t] = false
		}
	}
	extraTags, ok := channelWideTags[ts.ChannelID]
	if ok {
		for _, t := range extraTags {
			ts.Sanitized[t] = true
		}
	}
}

const (
	Lunduke          = "UCkK9UDm_ZNrq_rIXCz3xCGA"
	SwissExperiments = "UCNQfQvFMPnInwsU_iGYArJQ"
	Juggling         = "UC2fhTIbnQlFYaFzyTcmPkXg"
	JustJuggling     = "UCftqelpjmbFrUwr3VVzzVwA"
	JordanBPeterson  = "UCL_f53ZEJxp8TtlOkHwMV9Q"
)

var channelWideTags = map[string][]string{
	Lunduke:          {"linux", "technology"},
	SwissExperiments: {"science & technology", "experiments", "switzerland"},
	Juggling:         {"juggling", "circus arts", "malabares"},
	JustJuggling:     {"juggling", "circus arts", "malabares"},
	JordanBPeterson:  {"postmodernism", "psychology", "news"},
}
var tagsToSkip = map[string]*struct{}{
	"#hangoutsonair":                         nil,
	"#hoa":                                   nil,
	"1080p":                                  nil,
	"2":                                      nil,
	"2012":                                   nil,
	"2013":                                   nil,
	"2014":                                   nil,
	"2015":                                   nil,
	"2016":                                   nil,
	"2017":                                   nil,
	"2018":                                   nil,
	"2019":                                   nil,
	"360":                                    nil,
	"3d":                                     nil,
	"60fps":                                  nil,
	"720p":                                   nil,
	"achievement":                            nil,
	"action":                                 nil,
	"adam":                                   nil,
	"addon":                                  nil,
	"adityanath":                             nil,
	"africa":                                 nil,
	"african american":                       nil,
	"akshay kumar":                           nil,
	"alien":                                  nil,
	"all":                                    nil,
	"alpha":                                  nil,
	"amazing":                                nil,
	"america":                                nil,
	"amerika":                                nil,
	"and":                                    nil,
	"asia":                                   nil,
	"atlanta":                                nil,
	"atmospheric":                            nil,
	"attack":                                 nil,
	"aughad":                                 nil,
	"auto imagen":                            nil,
	"aventure":                               nil,
	"awesome":                                nil,
	"baba":                                   nil,
	"babas":                                  nil,
	"bakri":                                  nil,
	"bandar":                                 nil,
	"base":                                   nil,
	"battle":                                 nil,
	"battlefield":                            nil,
	"beard":                                  nil,
	"best":                                   nil,
	"beta":                                   nil,
	"betv":                                   nil,
	"bhagwa":                                 nil,
	"bharat":                                 nil,
	"bhawreshwara":                           nil,
	"bhoj":                                   nil,
	"bill still":                             nil,
	"black":                                  nil,
	"blackpeace72":                           nil,
	"blog":                                   nil,
	"blue":                                   nil,
	"bob lennon":                             nil,
	"bob":                                    nil,
	"bollywood news":                         nil,
	"bollywood tashan":                       nil,
	"bollywood":                              nil,
	"bounty":                                 nil,
	"build":                                  nil,
	"call":                                   nil,
	"camera":                                 nil,
	"campaign":                               nil,
	"canada":                                 nil,
	"challenge":                              nil,
	"challenges":                             nil,
	"champion":                               nil,
	"channel":                                nil,
	"chiara ferragni":                        nil,
	"chickens":                               nil,
	"china":                                  nil,
	"city":                                   nil,
	"clan":                                   nil,
	"clans":                                  nil,
	"clash of clans":                         nil,
	"clash royale":                           nil,
	"clash":                                  nil,
	"classic":                                nil,
	"colorful":                               nil,
	"commentary":                             nil,
	"compilation":                            nil,
	"convention":                             nil,
	"cool":                                   nil,
	"coplanet":                               nil,
	"cow":                                    nil,
	"craft":                                  nil,
	"crazy":                                  nil,
	"creative beard":                         nil,
	"csgo":                                   nil,
	"custom":                                 nil,
	"cyber locks":                            nil,
	"daily celebration":                      nil,
	"daily holidays":                         nil,
	"dark":                                   nil,
	"dave pacman":                            nil,
	"dave":                                   nil,
	"david di franco":                        nil,
	"david packman":                          nil,
	"david pacman":                           nil,
	"david pakman show":                      nil,
	"david pakman":                           nil,
	"david":                                  nil,
	"davidpakman.com":                        nil,
	"de":                                     nil,
	"dead":                                   nil,
	"dean":                                   nil,
	"death noise":                            nil,
	"death voice":                            nil,
	"deep":                                   nil,
	"defense":                                nil,
	"demo":                                   nil,
	"depression":                             nil,
	"deutsch":                                nil,
	"dfx":                                    nil,
	"dharm":                                  nil,
	"difranco":                               nil,
	"direct":                                 nil,
	"dnb portal":                             nil,
	"dnb":                                    nil,
	"dnbportal":                              nil,
	"download":                               nil,
	"drive":                                  nil,
	"easy":                                   nil,
	"eatmydiction1":                          nil,
	"eeuu":                                   nil,
	"empire":                                 nil,
	"ending":                                 nil,
	"energy":                                 nil,
	"english":                                nil,
	"entertainment":                          nil,
	"episode":                                nil,
	"erik":                                   nil,
	"europe":                                 nil,
	"fails":                                  nil,
	"fanta":                                  nil,
	"fantabobgames":                          nil,
	"farm":                                   nil,
	"farming":                                nil,
	"fast":                                   nil,
	"festival":                               nil,
	"fight":                                  nil,
	"fighter":                                nil,
	"fighting":                               nil,
	"fights":                                 nil,
	"fireworks":                              nil,
	"first":                                  nil,
	"fist":                                   nil,
	"florida":                                nil,
	"footage":                                nil,
	"for":                                    nil,
	"foto":                                   nil,
	"fr":                                     nil,
	"français":                               nil,
	"free":                                   nil,
	"friends":                                nil,
	"full hd":                                nil,
	"full":                                   nil,
	"fun":                                    nil,
	"futuristic":                             nil,
	"gaay":                                   nil,
	"gameplay fr":                            nil,
	"gamerworf":                              nil,
	"gamingoncaffeine":                       nil,
	"garena":                                 nil,
	"gay":                                    nil,
	"george senda":                           nil,
	"german":                                 nil,
	"get":                                    nil,
	"gift":                                   nil,
	"girl":                                   nil,
	"girls":                                  nil,
	"giveaway":                               nil,
	"glitch":                                 nil,
	"good":                                   nil,
	"google":                                 nil,
	"gopro":                                  nil,
	"gorthemoviegod":                         nil,
	"gps":                                    nil,
	"great":                                  nil,
	"green":                                  nil,
	"gt":                                     nil,
	"guide":                                  nil,
	"guy":                                    nil,
	"hangouts on air":                        nil,
	"hcg":                                    nil,
	"hd":                                     nil,
	"hdtv":                                   nil,
	"heroes of newerth":                      nil,
	"heroes":                                 nil,
	"high":                                   nil,
	"highlights":                             nil,
	"holiday everyday":                       nil,
	"hot":                                    nil,
	"house flipper":                          nil,
	"house party":                            nil,
	"houseparty":                             nil,
	"hungarian vlog":                         nil,
	"imagen":                                 nil,
	"imovie":                                 nil,
	"in":                                     nil,
	"inc":                                    nil,
	"india":                                  nil,
	"indonesia":                              nil,
	"industry (organization sector)":         nil,
	"influencer":                             nil,
	"injured":                                nil,
	"instagram":                              nil,
	"interior":                               nil,
	"interview":                              nil,
	"intro":                                  nil,
	"is":                                     nil,
	"it":                                     nil,
	"ita":                                    nil,
	"jaanwar":                                nil,
	"japan":                                  nil,
	"jay's":                                  nil,
	"jeux vidéo":                             nil,
	"jeux":                                   nil,
	"jew":                                    nil,
	"jnrsnr":                                 nil,
	"jnrsnrgaming":                           nil,
	"joe":                                    nil,
	"john sonmez":                            nil,
	"johnsp69":                               nil,
	"jump":                                   nil,
	"junior senior gaming":                   nil,
	"junior senior":                          nil,
	"kag3 entertainment":                     nil,
	"kag3":                                   nil,
	"karmakut":                               nil,
	"katrina kaif":                           nil,
	"kevin":                                  nil,
	"kids":                                   nil,
	"king":                                   nil,
	"kokesh":                                 nil,
	"kristomaster4":                          nil,
	"kutta":                                  nil,
	"la":                                     nil,
	"lance scurvin":                          nil,
	"lancescurv":                             nil,
	"latest bollywood news":                  nil,
	"launch":                                 nil,
	"legends":                                nil,
	"lennon":                                 nil,
	"liberal news":                           nil,
	"life is strange":                        nil,
	"life":                                   nil,
	"like":                                   nil,
	"liquid":                                 nil,
	"live stream":                            nil,
	"live":                                   nil,
	"livestream":                             nil,
	"london":                                 nil,
	"lp":                                     nil,
	"magyar vlog":                            nil,
	"magyar vlogger":                         nil,
	"make":                                   nil,
	"man":                                    nil,
	"map":                                    nil,
	"martinez ca":                            nil,
	"maskedmage":                             nil,
	"michigan":                               nil,
	"mine":                                   nil,
	"minimal":                                nil,
	"mission":                                nil,
	"mmr":                                    nil,
	"mobile":                                 nil,
	"mode":                                   nil,
	"modi":                                   nil,
	"moments":                                nil,
	"monster":                                nil,
	"montage":                                nil,
	"moon":                                   nil,
	"mortal":                                 nil,
	"multicolored":                           nil,
	"music":                                  nil,
	"my":                                     nil,
	"narendra":                               nil,
	"navidad":                                nil,
	"neurofunk":                              nil,
	"new":                                    nil,
	"nickatnyte":                             nil,
	"nidge":                                  nil,
	"night":                                  nil,
	"nma":                                    nil,
	"no commentary":                          nil,
	"no":                                     nil,
	"noise":                                  nil,
	"north":                                  nil,
	"obiettivo":                              nil,
	"of":                                     nil,
	"official":                               nil,
	"old":                                    nil,
	"on":                                     nil,
	"one":                                    nil,
	"opening":                                nil,
	"ops":                                    nil,
	"orange":                                 nil,
	"outrageous":                             nil,
	"overview":                               nil,
	"packman":                                nil,
	"pakman":                                 nil,
	"part 1":                                 nil,
	"part":                                   nil,
	"party":                                  nil,
	"paul":                                   nil,
	"ped":                                    nil,
	"pewdiepie":                              nil,
	"pig":                                    nil,
	"pittsburgh pa":                          nil,
	"plus":                                   nil,
	"podcastradio":                           nil,
	"police":                                 nil,
	"power":                                  nil,
	"pradesh":                                nil,
	"prakriti":                               nil,
	"premiere":                               nil,
	"preview":                                nil,
	"price":                                  nil,
	"productions":                            nil,
	"progressive news":                       nil,
	"progressive podcast":                    nil,
	"quality":                                nil,
	"radio":                                  nil,
	"raebareli":                              nil,
	"rage":                                   nil,
	"raid":                                   nil,
	"rants":                                  nil,
	"react":                                  nil,
	"reaction":                               nil,
	"real":                                   nil,
	"red":                                    nil,
	"relationships":                          nil,
	"release":                                nil,
	"replay":                                 nil,
	"replica":                                nil,
	"review":                                 nil,
	"road":                                   nil,
	"russia":                                 nil,
	"sadhguru":                               nil,
	"sadhu":                                  nil,
	"samaj":                                  nil,
	"sant":                                   nil,
	"santa":                                  nil,
	"scary":                                  nil,
	"scene":                                  nil,
	"scoope":                                 nil,
	"scurv":                                  nil,
	"scurvin":                                nil,
	"segui":                                  nil,
	"series":                                 nil,
	"sex":                                    nil,
	"sexy":                                   nil,
	"shahrukh khan":                          nil,
	"sharefactory™":                          nil,
	"shield":                                 nil,
	"shooter":                                nil,
	"show":                                   nil,
	"shyam":                                  nil,
	"sikh":                                   nil,
	"silver":                                 nil,
	"simple programmer":                      nil,
	"simpleprogrammer.com":                   nil,
	"slime":                                  nil,
	"solo":                                   nil,
	"sonny daniel vlogs":                     nil,
	"sonny daniel":                           nil,
	"sonnydaniel":                            nil,
	"source":                                 nil,
	"speed":                                  nil,
	"spreaker":                               nil,
	"squad ops":                              nil,
	"squad":                                  nil,
	"sri":                                    nil,
	"states":                                 nil,
	"story":                                  nil,
	"street":                                 nil,
	"suar":                                   nil,
	"super":                                  nil,
	"support":                                nil,
	"szekely":                                nil,
	"szekelyvegan":                           nil,
	"székely vegán":                          nil,
	"székelyvegán":                           nil,
	"taiwanese animation":                    nil,
	"taiwanese animators":                    nil,
	"talk radio":                             nil,
	"talk":                                   nil,
	"tanyázás":                               nil,
	"tdps":                                   nil,
	"team":                                   nil,
	"television":                             nil,
	"terror":                                 nil,
	"test":                                   nil,
	"texas":                                  nil,
	"thailand":                               nil,
	"the brotherhood of gaming":              nil,
	"the david pakman show":                  nil,
	"the guy from pittsburgh":                nil,
	"the kag3 gaming":                        nil,
	"the kag3":                               nil,
	"the lancescurv show":                    nil,
	"the":                                    nil,
	"thecreativeone":                         nil,
	"thefantasio974":                         nil,
	"time":                                   nil,
	"tips":                                   nil,
	"to":                                     nil,
	"tom":                                    nil,
	"tomo news":                              nil,
	"tomonews":                               nil,
	"tona":                                   nil,
	"top":                                    nil,
	"total":                                  nil,
	"totka":                                  nil,
	"trevor":                                 nil,
	"trick":                                  nil,
	"tricks":                                 nil,
	"trofeo":                                 nil,
	"trolling":                               nil,
	"true":                                   nil,
	"truetotalempireinc":                     nil,
	"turbo":                                  nil,
	"tv":                                     nil,
	"uct-wqktykk1_70u4bb4k4lq":               nil,
	"uk":                                     nil,
	"ultimate":                               nil,
	"uniqornaments":                          nil,
	"unique":                                 nil,
	"united":                                 nil,
	"until dawn":                             nil,
	"up":                                     nil,
	"update":                                 nil,
	"us":                                     nil,
	"usa":                                    nil,
	"uttar":                                  nil,
	"vaanar":                                 nil,
	"video":                                  nil,
	"videos":                                 nil,
	"vlog":                                   nil,
	"vlogger":                                nil,
	"vlogs":                                  nil,
	"voice over":                             nil,
	"voice":                                  nil,
	"vs":                                     nil,
	"vulcanhdgaming":                         nil,
	"waale":                                  nil,
	"white":                                  nil,
	"willie pelissier":                       nil,
	"willie":                                 nil,
	"win":                                    nil,
	"with":                                   nil,
	"women":                                  nil,
	"wordofgod":                              nil,
	"wounded":                                nil,
	"wow":                                    nil,
	"x320":                                   nil,
	"you":                                    nil,
	"youtube capture":                        nil,
	"youtube editor":                         nil,
	"youtube":                                nil,
	"youtuber":                               nil,
	"ytquality=high":                         nil,
	"{5859dfec-026f-46ba-bea0-02bf43aa1a6f}": nil,
	"игра":                                   nil,
	"игры для девочек":                       nil,
	"игры для мальчиков":                     nil,
	"игры":                                   nil,
	"летсплей":                               nil,
	"прохождение игры":                       nil,
	"прохождение":                            nil,
	"рпг":                                    nil,
	"เกม":                                    nil,
}
var mapAndReplace = map[string]string{
	"nfl":                            Sports,
	"minecraft (award-winning work)": Gaming,
	"minecraft survival":             Gaming,
	"modded minecraft":               Gaming,
	"minecraft movie":                Gaming,
	"minecraft videos":               Gaming,
}

var mapAndKeep = map[string]string{
	"dance":                               Art,
	"design":                              Art,
	"fashion":                             Art,
	"creative hairstyles":                 Art,
	"colorful hair":                       Art,
	"cool long hair":                      Art,
	"cartoon":                             Art,
	"comic":                               Art,
	"comics":                              Art,
	"beauty":                              Art,
	"car":                                 Automotive,
	"cars":                                Automotive,
	"4x4":                                 Automotive,
	"automobile":                          Automotive,
	"autos":                               Automotive,
	"carros":                              Automotive,
	"suv":                                 Automotive,
	"truck":                               Automotive,
	"garage":                              Automotive,
	"auto":                                Automotive,
	"crash":                               Automotive,
	"driving":                             Automotive,
	"race":                                Automotive,
	"bmw":                                 Automotive,
	"vehicle":                             Automotive,
	"benz":                                Automotive,
	"auto show (event)":                   Automotive,
	"engine":                              Automotive,
	"mercedes":                            Automotive,
	"motorcycle":                          Automotive,
	"porsche":                             Automotive,
	"bus":                                 Automotive,
	"jeep":                                Automotive,
	"secular talk":                        Beliefs,
	"atheist":                             Beliefs,
	"atheism":                             Beliefs,
	"agnostic":                            Beliefs,
	"freedom":                             Beliefs,
	"secular":                             Beliefs,
	"religion":                            Beliefs,
	"liberty":                             Beliefs,
	"christian":                           Beliefs,
	"god":                                 Beliefs,
	"libertarian":                         Beliefs,
	"guru":                                Beliefs,
	"muslim":                              Beliefs,
	"voluntarism":                         Beliefs,
	"yogi":                                Beliefs,
	"mystic":                              Beliefs,
	"bible":                               Beliefs,
	"jesus":                               Beliefs,
	"anarchism":                           Beliefs,
	"christianity":                        Beliefs,
	"anarchy":                             Beliefs,
	"voluntaryist":                        Beliefs,
	"activism":                            Beliefs,
	"hindu":                               Beliefs,
	"peace":                               Beliefs,
	"love":                                Beliefs,
	"death":                               Beliefs,
	"christmas":                           Beliefs,
	"lord":                                Beliefs,
	"bitcoin":                             Blockchain,
	"cryptocurrency":                      Blockchain,
	"crypto":                              Blockchain,
	"ethereum":                            Blockchain,
	"btc":                                 Blockchain,
	"airdrop":                             Blockchain,
	"litecoin":                            Blockchain,
	"eth":                                 Blockchain,
	"mining":                              Blockchain,
	"bitcoin news":                        Blockchain,
	"ico":                                 Blockchain,
	"crypto news":                         Blockchain,
	"token":                               Blockchain,
	"token free":                          Blockchain,
	"bitcoin price":                       Blockchain,
	"altcoins":                            Blockchain,
	"cryptocurrency news":                 Blockchain,
	"altcoin":                             Blockchain,
	"coin":                                Blockchain,
	"ripple":                              Blockchain,
	"free bitcoin":                        Blockchain,
	"ltc":                                 Blockchain,
	"dash":                                Blockchain,
	"eos":                                 Blockchain,
	"steemit":                             Blockchain,
	"coinbase":                            Blockchain,
	"cryptocurrencies":                    Blockchain,
	"money":                               Economics,
	"economy":                             Economics,
	"gold":                                Economics,
	"federal reserve":                     Economics,
	"market":                              Economics,
	"investing":                           Economics,
	"dollar":                              Economics,
	"monetary reform":                     Economics,
	"economic":                            Economics,
	"recession":                           Economics,
	"trading":                             Economics,
	"finance":                             Economics,
	"currency":                            Economics,
	"business":                            Economics,
	"health":                              Food,
	"vegan":                               Food,
	"fruits":                              Food,
	"vegán":                               Food,
	"food holidays":                       Food,
	"fun":                                 Funny,
	"funny":                               Funny,
	"hilarious":                           Funny,
	"lol":                                 Funny,
	"humor":                               Funny,
	"funny moments":                       Funny,
	"comedy":                              Funny,
	"parody":                              Funny,
	"funny video":                         Funny,
	"silly":                               Funny,
	"humour":                              Funny,
	"satire":                              Funny,
	"walkthrough":                         Gaming,
	"#ps4live":                            Gaming,
	"twitch":                              Gaming,
	"#ps4share":                           Gaming,
	"gaming":                              Gaming,
	"video game":                          Gaming,
	"playstation":                         Gaming,
	"xbox one":                            Gaming,
	"video games":                         Gaming,
	"lets":                                Gaming,
	"nintendo":                            Gaming,
	"fps":                                 Gaming,
	"video game (industry)":               Gaming,
	"multiplayer":                         Gaming,
	"fortnite":                            Gaming,
	"dota 2":                              Gaming,
	"xbox 360":                            Gaming,
	"sony computer entertainment":         Gaming,
	"pc games":                            Gaming,
	"call of duty":                        Gaming,
	"pokemon":                             Gaming,
	"league":                              Gaming,
	"let's play":                          Gaming,
	"let's":                               Gaming,
	"league of legends":                   Gaming,
	"league of legends (video game)":      Gaming,
	"cod":                                 Gaming,
	"pubg":                                Gaming,
	"xbox":                                Gaming,
	"pvp":                                 Gaming,
	"videogame":                           Gaming,
	"dota":                                Gaming,
	"games":                               Gaming,
	"let's play fr":                       Gaming,
	"mario":                               Gaming,
	"pc game":                             Gaming,
	"ps4":                                 Gaming,
	"let":                                 Gaming,
	"fallout 4":                           Gaming,
	"shooter game (media genre)":          Gaming,
	"playthrough":                         Gaming,
	"gamer":                               Gaming,
	"wii":                                 Gaming,
	"playing":                             Gaming,
	"computer game games":                 Gaming,
	"gameplay":                            Gaming,
	"arcade":                              Gaming,
	"video game culture":                  Gaming,
	"xbox 360 (video game platform)":      Gaming,
	"rpg":                                 Gaming,
	"game":                                Gaming,
	"gta":                                 Gaming,
	"let’s play":                          Gaming,
	"minecraft":                           Gaming,
	"skyrim":                              Gaming,
	"action-adventure game (media genre)": Gaming,
	"sony interactive entertainment":      Gaming,
	"dlc":                                 Gaming,
	"xbox360":                             Gaming,
	"zelda":                               Gaming,
	"steam":                               Gaming,
	"capcom":                              Gaming,
	"fortnite battle royale":              Gaming,
	"singleplayer":                        Gaming,
	"pacman":                              Gaming,
	"gta 5":                               Gaming,
	"grand theft auto v":                  Gaming,
	"valve":                               Gaming,
	"massively multiplayer online role-playing game (video game genre)": Gaming,
	"#gaming":                               Gaming,
	"halo":                                  Gaming,
	"computer games":                        Gaming,
	"nintendo switch":                       Gaming,
	"3d games":                              Gaming,
	"ps2":                                   Gaming,
	"role-playing video game (media genre)": Gaming,
	"supercell":                             Gaming,
	"dota2":                                 Gaming,
	"sims":                                  Gaming,
	"pc gaming":                             Gaming,
	"playstation 4":                         Gaming,
	"battle royale":                         Gaming,
	"rpg games":                             Gaming,
	"sims 4":                                Gaming,
	"roblox":                                Gaming,
	"mw3":                                   Gaming,
	"far cry 5":                             Gaming,
	"squad gameplay":                        Gaming,
	"tf2":                                   Gaming,
	"ps3":                                   Gaming,
	"resident evil":                         Gaming,
	"indie game":                            Gaming,
	"overwatch":                             Gaming,
	"brawl":                                 Gaming,
	"call of duty®: black ops iii":          Gaming,
	"console":                               Gaming,
	"mugen":                                 Gaming,
	"play":                                  Gaming,
	"mass effect":                           Gaming,
	"ubisoft":                               Gaming,
	"minecraft: playstation®4 edition":      Gaming,
	"rts":                                   Gaming,
	"mmorpg":                                Gaming,
	"first person shooter":                  Gaming,
	"action role-playing game (video game genre)": Gaming,
	"role-playing game (game genre)":              Gaming,
	"sonic":                                       Gaming,
	"videogames":                                  Gaming,
	"level":                                       Gaming,
	"sims 3":                                      Gaming,
	"esports":                                     Gaming,
	"minecraft (video game)":                      Gaming,
	"simulator":                                   Gaming,
	"horrible gamers":                             Gaming,
	"moba":                                        Gaming,
	"the game":                                    Gaming,
	"link":                                        Gaming,
	"game reviews":                                Gaming,
	"sims 5":                                      Gaming,
	"snk":                                         Gaming,
	"online games":                                Gaming,
	"squad game":                                  Gaming,
	"switch":                                      Gaming,
	"lets play":                                   Gaming,
	"portal":                                      Gaming,
	"boss":                                        Gaming,
	"mod":                                         Gaming,
	"strategy":                                    Gaming,
	"stream":                                      Gaming,
	"galaxy":                                      Gaming,
	"tutorial":                                    Learning,
	"how to":                                      Learning,
	"educational":                                 Learning,
	"how":                                         Learning,
	"salman khan":                                 Learning,
	"education":                                   Learning,
	"help":                                        Learning,
	"lessons":                                     Learning,
	"online learning":                             Learning,
	"diy":                                         Learning,
	"school":                                      Learning,
	"how-to":                                      Learning,
	"howto":                                       Learning,
	"advice":                                      Learning,
	"history":                                     Learning,
	"inspirational":                               Learning,
	"drum and bass":                               Music,
	"bass":                                        Music,
	"dubstep":                                     Music,
	"song":                                        Music,
	"rap":                                         Music,
	"remix":                                       Music,
	"drum":                                        Music,
	"house":                                       Music,
	"drum bass":                                   Music,
	"darkstep":                                    Music,
	"guitar":                                      Music,
	"drumstep":                                    Music,
	"techstep":                                    Music,
	"metal":                                       Music,
	"dj":                                          Music,
	"rock":                                        Music,
	"new music":                                   Music,
	"hip hop":                                     Music,
	"cover":                                       Music,
	"instrumental":                                Music,
	"electronic":                                  Music,
	"alternative":                                 Music,
	"space":                                       Nature,
	"plants":                                      Nature,
	"trees":                                       Nature,
	"eggs":                                        Nature,
	"flowers":                                     Nature,
	"beach":                                       Nature,
	"rainbow":                                     Nature,
	"water":                                       Nature,
	"animals":                                     Nature,
	"floral":                                      Nature,
	"gardening":                                   Nature,
	"garden":                                      Nature,
	"world":                                       Nature,
	"dog":                                         Nature,
	"travel":                                      Nature,
	"rv":                                          Nature,
	"survival":                                    Nature,
	"outdoor":                                     Nature,
	"full time rving":                             Nature,
	"rv park":                                     Nature,
	"travel trailer":                              Nature,
	"environment":                                 Nature,
	"news":                                        News,
	"democrat":                                    News,
	"liberal":                                     News,
	"progressive":                                 News,
	"government":                                  News,
	"republican":                                  News,
	"conservative":                                News,
	"commentary":                                  News,
	"political":                                   News,
	"cnn":                                         News,
	"cbs":                                         News,
	"msnbc":                                       News,
	"fox news":                                    News,
	"fox":                                         News,
	"nbc":                                         News,
	"politics":                                    News,
	"news & politics":                             News,
	"senate":                                      News,
	"congress":                                    News,
	"house of representatives":                    News,
	"video news":                                  News,
	"animated news":                               News,
	"como":                                        News,
	"putin":                                       News,
	"news radio":                                  News,
	"hillary clinton":                             News,
	"progressive talk":                            News,
	"trump":                                       News,
	"barack obama":                                News,
	"donald trump":                                News,
	"newscast":                                    News,
	"racism":                                      News,
	"war":                                         News,
	"horror":                                      PopCulture,
	"zombies":                                     PopCulture,
	"next media animation":                        PopCulture,
	"adventure":                                   PopCulture,
	"epic":                                        PopCulture,
	"reviews":                                     PopCulture,
	"movie":                                       PopCulture,
	"indie":                                       PopCulture,
	"pro":                                         PopCulture,
	"animation":                                   PopCulture,
	"zombie":                                      PopCulture,
	"star":                                        PopCulture,
	"film":                                        PopCulture,
	"magic":                                       PopCulture,
	"ninja":                                       PopCulture,
	"top 10":                                      PopCulture,
	"wwe":                                         PopCulture,
	"loot":                                        PopCulture,
	"marvel":                                      PopCulture,
	"manga":                                       PopCulture,
	"puzzle":                                      PopCulture,
	"hero":                                        PopCulture,
	"retro":                                       PopCulture,
	"disney":                                      PopCulture,
	"dc":                                          PopCulture,
	"next animation studio":                       PopCulture,
	"cosplay":                                     PopCulture,
	"dragoncon":                                   PopCulture,
	"comiccon":                                    PopCulture,
	"stories":                                     PopCulture,
	"unboxing":                                    PopCulture,
	"fail":                                        PopCulture,
	"dragon":                                      PopCulture,
	"meme":                                        PopCulture,
	"family friendly":                             PopCulture,
	"random":                                      PopCulture,
	"vlogging":                                    PopCulture,
	"react":                                       PopCulture,
	"trailer":                                     PopCulture,
	"reaction":                                    PopCulture,
	"toys":                                        PopCulture,
	"reacts":                                      PopCulture,
	"cute":                                        PopCulture,
	"weed":                                        PopCulture,
	"drunkfx":                                     PopCulture,
	"happy":                                       PopCulture,
	"anime":                                       PopCulture,
	"family":                                      PopCulture,
	"memes":                                       PopCulture,
	"wtf":                                         PopCulture,
	"racing":                                      Sports,
	"sport":                                       Sports,
	"training":                                    Sports,
	"football":                                    Sports,
	"computer":                                    Technology,
	"online":                                      Technology,
	"mods":                                        Technology,
	"tech":                                        Technology,
	"linux":                                       Technology,
	"sony":                                        Technology,
	"iphone":                                      Technology,
	"pc":                                          Technology,
	"ram":                                         Technology,
	"samsung":                                     Technology,
	"software":                                    Technology,
	"windows":                                     Technology,
	"programming":                                 Technology,
	"simulation":                                  Technology,
	"facebook":                                    Technology,
	"desktop":                                     Technology,
	"install":                                     Technology,
	"microsoft":                                   Technology,
	"twitter":                                     Technology,
	"android":                                     Technology,
	"mobile":                                      Technology,
	"apple":                                       Technology,
	"ios":                                         Technology,
	"server":                                      Technology,
	"nvidia":                                      Technology,
	"open source":                                 Technology,
	"apps":                                        Technology,
	"laptop":                                      Technology,
	"podcast":                                     Technology,
	"hack":                                        Technology,
	"guns":                                        Weapons,
	"shooting":                                    Weapons,
	"trophy":                                      Weapons,
	"combat":                                      Weapons,
	"fire":                                        Weapons,
	"gun":                                         Weapons,
	"tactical":                                    Weapons,
	"firearms":                                    Weapons,
	"rocket":                                      Weapons,
	"sniper":                                      Weapons,
	"knife":                                       Weapons,
	"trap":                                        Weapons,
	"assault":                                     Weapons,
}
