package tagsManager

const (
	Gaming     = "gaming"
	Blockchain = "blockchain"
	News       = "news"
	Learning   = "learning"
	Funny      = "funny"
	Technology = "technology"
	Automotive = "automotive"
	Economics  = "economics"
	Sports     = "sports"
	Food       = "food"
	Science    = "science"
	Art        = "art"
	Nature     = "nature"
	Beliefs    = "beliefs"
	Music      = "music"
	PopCulture = "pop culture"
	Weapons    = "weapons"
)

func SanitizeTags(tags []string) []string {
	ts := &tagsSanitizer{
		Unsanitized: tags,
	}
	ts.init()
	ts.cleanup()
	ts.replace()
	ts.add()

	sanitizedTags := make([]string, len(ts.Sanitized))
	index := 0
	for t := range ts.Sanitized {
		sanitizedTags[index] = t
		index++
	}
	return sanitizedTags
}

type tagsSanitizer struct {
	Unsanitized []string
	Sanitized   map[string]bool
}

func (ts *tagsSanitizer) init() {
	if len(ts.Sanitized) == 0 {
		ts.Sanitized = make(map[string]bool, len(ts.Unsanitized)+14)
	}
}

func (ts *tagsSanitizer) cleanup() {
	for _, t := range ts.Unsanitized {
		_, ok := tagsToSkip[t]
		if !ok {
			ts.Sanitized[t] = true
		}
	}
}

func (ts *tagsSanitizer) replace() {
	for _, t := range ts.Unsanitized {
		match, filterMatch := mapAndReplace[t]
		if filterMatch {
			delete(ts.Sanitized, t)
			ts.Sanitized[match] = true
		}
	}
}

func (ts *tagsSanitizer) add() {
	for _, t := range ts.Unsanitized {
		match, filterMatch := mapAndKeep[t]
		if filterMatch {
			ts.Sanitized[match] = true
			ts.Sanitized[t] = true
		}
	}
}

var tagsToSkip = map[string]*struct{}{
	"video":                                  nil,
	"review":                                 nil,
	"youtube":                                nil,
	"david packman":                          nil,
	"2018":                                   nil,
	"new":                                    nil,
	"the":                                    nil,
	"music":                                  nil,
	"hd":                                     nil,
	"talk":                                   nil,
	"entertainment":                          nil,
	"Radio":                                  nil,
	"2017":                                   nil,
	"live":                                   nil,
	"free":                                   nil,
	"america":                                nil,
	"of":                                     nil,
	"david pakman":                           nil,
	"dave pacman":                            nil,
	"pakman":                                 nil,
	"davidpakman.com":                        nil,
	"tdps":                                   nil,
	"1080p":                                  nil,
	"united":                                 nil,
	"david pakman show":                      nil,
	"states":                                 nil,
	"europe":                                 nil,
	"tomonews":                               nil,
	"Tomonews":                               nil,
	"2016":                                   nil,
	"eeuu":                                   nil,
	"REVIEW":                                 nil,
	"Launch":                                 nil,
	"taiwanese animators":                    nil,
	"best":                                   nil,
	"TURBO":                                  nil,
	"television":                             nil,
	"gt":                                     nil,
	"USA":                                    nil,
	"GPS":                                    nil,
	"PREMIERE":                               nil,
	"guide":                                  nil,
	"scoope":                                 nil,
	"US":                                     nil,
	"nma":                                    nil,
	"Nma":                                    nil,
	"to":                                     nil,
	"auto imagen":                            nil,
	"tips":                                   nil,
	"action":                                 nil,
	"download":                               nil,
	"david pacman":                           nil,
	"taiwanese animation":                    nil,
	"Taiwanese animation":                    nil,
	"YouTube Editor":                         nil,
	"Tomo news":                              nil,
	"replay":                                 nil,
	"update":                                 nil,
	"battle":                                 nil,
	"2019":                                   nil,
	"story":                                  nil,
	"one":                                    nil,
	"spreaker":                               nil,
	"Jay's":                                  nil,
	"episode":                                nil,
	"for":                                    nil,
	"SHAREfactory™":                          nil,
	"#hangoutsonair":                         nil,
	"#hoa":                                   nil,
	"vs":                                     nil,
	"bob":                                    nil,
	"dnb portal":                             nil,
	"instagram":                              nil,
	"challenge":                              nil,
	"eatmydiction1":                          nil,
	"usa":                                    nil,
	"français":                               nil,
	"live stream":                            nil,
	"top":                                    nil,
	"fr":                                     nil,
	"fanta":                                  nil,
	"HD":                                     nil,
	"and":                                    nil,
	"foto":                                   nil,
	"no":                                     nil,
	"720p":                                   nil,
	"up":                                     nil,
	"radio":                                  nil,
	"david":                                  nil,
	"russia":                                 nil,
	"ytquality=high":                         nil,
	"part":                                   nil,
	"bollywood tashan":                       nil,
	"bounty":                                 nil,
	"dnb":                                    nil,
	"highlights":                             nil,
	"thefantasio974":                         nil,
	"great":                                  nil,
	"man":                                    nil,
	"replica":                                nil,
	"red":                                    nil,
	"chiara ferragni":                        nil,
	"in":                                     nil,
	"bob lennon":                             nil,
	"series":                                 nil,
	"life":                                   nil,
	"first":                                  nil,
	"dnbportal":                              nil,
	"fantabobgames":                          nil,
	"segui":                                  nil,
	"lennon":                                 nil,
	"neurofunk":                              nil,
	"on":                                     nil,
	"kag3":                                   nil,
	"2015":                                   nil,
	"ITA":                                    nil,
	"gamerworf":                              nil,
	"chickens":                               nil,
	"uct-wqktykk1_70u4bb4k4lq":               nil,
	"beard":                                  nil,
	"videos":                                 nil,
	"nidge":                                  nil,
	"bill still":                             nil,
	"nickatnyte":                             nil,
	"прохождение":                            nil,
	"minimal":                                nil,
	"clash":                                  nil,
	"trofeo":                                 nil,
	"attack":                                 nil,
	"test":                                   nil,
	"DFX":                                    nil,
	"india":                                  nil,
	"police":                                 nil,
	"campaign":                               nil,
	"tricks":                                 nil,
	"depression":                             nil,
	"unique":                                 nil,
	"Bharat":                                 nil,
	"imagen":                                 nil,
	"LanceScurv":                             nil,
	"us":                                     nil,
	"google":                                 nil,
	"defense":                                nil,
	"gameplay fr":                            nil,
	"giveaway":                               nil,
	"hot":                                    nil,
	"Interior":                               nil,
	"show":                                   nil,
	"YouTube Capture":                        nil,
	"jump":                                   nil,
	"2014":                                   nil,
	"thailand":                               nil,
	"santa":                                  nil,
	"ultimate":                               nil,
	"deutsch":                                nil,
	"mission":                                nil,
	"The Lancescurv Show":                    nil,
	"Legends":                                nil,
	"modi":                                   nil,
	"noise":                                  nil,
	"Texas":                                  nil,
	"china":                                  nil,
	"Scurv":                                  nil,
	"gift":                                   nil,
	"sikh":                                   nil,
	"night":                                  nil,
	"Episode":                                nil,
	"good":                                   nil,
	"plus":                                   nil,
	"szekelyvegan":                           nil,
	"székelyvegán":                           nil,
	"szekely":                                nil,
	"игра":                                   nil,
	"is":                                     nil,
	"székely vegán":                          nil,
	"john sonmez":                            nil,
	"jew":                                    nil,
	"magyar vlogger":                         nil,
	"magyar vlog":                            nil,
	"hungarian vlog":                         nil,
	"baba":                                   nil,
	"montage":                                nil,
	"New":                                    nil,
	"squad":                                  nil,
	"german":                                 nil,
	"amerika":                                nil,
	"full":                                   nil,
	"sri":                                    nil,
	"kristomaster4":                          nil,
	"narendra":                               nil,
	"sant":                                   nil,
	"adityanath":                             nil,
	"sadhguru":                               nil,
	"ped":                                    nil,
	"Sadhu":                                  nil,
	"Shyam":                                  nil,
	"dharm":                                  nil,
	"babas":                                  nil,
	"gaay":                                   nil,
	"Pradesh":                                nil,
	"Raebareli":                              nil,
	"waale":                                  nil,
	"Uttar":                                  nil,
	"Bandar":                                 nil,
	"kutta":                                  nil,
	"bakri":                                  nil,
	"aughad":                                 nil,
	"suar":                                   nil,
	"jaanwar":                                nil,
	"tona":                                   nil,
	"bhawreshwara":                           nil,
	"vaanar":                                 nil,
	"bhagwa":                                 nil,
	"prakriti":                               nil,
	"samaj":                                  nil,
	"totka":                                  nil,
	"bhoj":                                   nil,
	"dave":                                   nil,
	"vulcanhdgaming":                         nil,
	"fast":                                   nil,
	"moon":                                   nil,
	"scene":                                  nil,
	"tv":                                     nil,
	"2":                                      nil,
	"fighter":                                nil,
	"NEW":                                    nil,
	"jeux":                                   nil,
	"игры":                                   nil,
	"tanyázás":                               nil,
	"obiettivo":                              nil,
	"csgo":                                   nil,
	"The guy From Pittsburgh":                nil,
	"blue":                                   nil,
	"youtuber":                               nil,
	"clash royale":                           nil,
	"SHOW":                                   nil,
	"johnsp69":                               nil,
	"japan":                                  nil,
	"YouTube":                                nil,
	"The David Pakman Show":                  nil,
	"thecreativeone":                         nil,
	"Youtube":                                nil,
	"classic":                                nil,
	"Talk Radio":                             nil,
	"white":                                  nil,
	"летсплей":                               nil,
	"clash of clans":                         nil,
	"Industry (Organization Sector)":         nil,
	"difranco":                               nil,
	"custom":                                 nil,
	"прохождение игры":                       nil,
	"progressive podcast":                    nil,
	"george Senda":                           nil,
	"360":                                    nil,
	"betv":                                   nil,
	"gamingoncaffeine":                       nil,
	"Drive":                                  nil,
	"Africa":                                 nil,
	"progressive news":                       nil,
	"full hd":                                nil,
	"Asia":                                   nil,
	"liberal news":                           nil,
	"packman":                                nil,
	"hdtv":                                   nil,
	"Entertainment":                          nil,
	"Simple Programmer":                      nil,
	"indonesia":                              nil,
	"karmakut":                               nil,
	"gorthemoviegod":                         nil,
	"Lance scurvin":                          nil,
	"silver":                                 nil,
	"clans":                                  nil,
	"игры для мальчиков":                     nil,
	"игры для девочек":                       nil,
	"blackpeace72":                           nil,
	"multicolored":                           nil,
	"intro":                                  nil,
	"creative beard":                         nil,
	"cyber locks":                            nil,
	"uniqornaments":                          nil,
	"daily holidays":                         nil,
	"daily celebration":                      nil,
	"holiday everyday":                       nil,
	"3d":                                     nil,
	"lp":                                     nil,
	"interview":                              nil,
	"Heroes":                                 nil,
	"maskedmage":                             nil,
	"рпг":                                    nil,
	"north":                                  nil,
	"road":                                   nil,
	"monster":                                nil,
	"de":                                     nil,
	"mode":                                   nil,
	"podcastradio":                           nil,
	"Man":                                    nil,
	"preview":                                nil,
	"rage":                                   nil,
	"map":                                    nil,
	"Pittsburgh pa":                          nil,
	"david di franco":                        nil,
	"win":                                    nil,
	"junior senior":                          nil,
	"demo":                                   nil,
	"paul":                                   nil,
	"simpleprogrammer.com":                   nil,
	"2013":                                   nil,
	"green":                                  nil,
	"la":                                     nil,
	"footage":                                nil,
	"london":                                 nil,
	"adam":                                   nil,
	"jnrsnrgaming":                           nil,
	"jnrsnr":                                 nil,
	"TRUE":                                   nil,
	"junior senior gaming":                   nil,
	"the kag3 gaming":                        nil,
	"sonny daniel":                           nil,
	"atlanta":                                nil,
	"wordofgod":                              nil,
	"2012":                                   nil,
	"Katrina kaif":                           nil,
	"English":                                nil,
	"Addon":                                  nil,
	"High":                                   nil,
	"To":                                     nil,
	"willie":                                 nil,
	"it":                                     nil,
	"trolling":                               nil,
	"Bollywood news":                         nil,
	"willie pelissier":                       nil,
	"canada":                                 nil,
	"productions":                            nil,
	"iMovie":                                 nil,
	"channel":                                nil,
	"total":                                  nil,
	"trick":                                  nil,
	"the kag3":                               nil,
	"Scurvin":                                nil,
	"Free":                                   nil,
	"make":                                   nil,
	"The":                                    nil,
	"ops":                                    nil,
	"trevor":                                 nil,
	"kevin":                                  nil,
	"life is strange":                        nil,
	"you":                                    nil,
	"kokesh":                                 nil,
	"the brotherhood of gaming":              nil,
	"Martinez ca":                            nil,
	"real":                                   nil,
	"เกม":                                    nil,
	"sonny daniel vlogs":                     nil,
	"China":                                  nil,
	"African American":                       nil,
	"Slime":                                  nil,
	"America":                                nil,
	"price":                                  nil,
	"michigan":                               nil,
	"call":                                   nil,
	"truetotalempireinc":                     nil,
	"Akshay Kumar":                           nil,
	"Shield":                                 nil,
	"aventure":                               nil,
	"until dawn":                             nil,
	"mortal":                                 nil,
	"camera":                                 nil,
	"Team":                                   nil,
	"release":                                nil,
	"get":                                    nil,
	"florida":                                nil,
	"with":                                   nil,
	"battlefield":                            nil,
	"joe":                                    nil,
	"tom":                                    nil,
	"Atmospheric":                            nil,
	"squad ops":                              nil,
	"overview":                               nil,
	"fist":                                   nil,
	"clan":                                   nil,
	"guy":                                    nil,
	"sonnydaniel":                            nil,
	"Voice Over":                             nil,
	"Test":                                   nil,
	"HouseParty":                             nil,
	"ending":                                 nil,
	"my":                                     nil,
	"garena":                                 nil,
	"kag3 entertainment":                     nil,
	"{5859dfec-026f-46ba-bea0-02bf43aa1a6f}": nil,
	"shahrukh Khan":                          nil,
	"Opening":                                nil,
	"erik":                                   nil,
	"part 1":                                 nil,
	"UK":                                     nil,
	"dean":                                   nil,
	"hcg":                                    nil,
	"60fps":                                  nil,
	"latest Bollywood news":                  nil,
	"all":                                    nil,
	"x320":                                   nil,
	"orange":                                 nil,
	"pig":                                    nil,
	"cow":                                    nil,
	"convention":                             nil,
	"easy":                                   nil,
	"achievement":                            nil,
	"direct":                                 nil,
	"glitch":                                 nil,
	"farming":                                nil,
	"mine":                                   nil,
	"wow":                                    nil,
	"empire":                                 nil,
	"inc":                                    nil,
	"source":                                 nil,
	"heroes of newerth":                      nil,
	"vlog":                                   nil,
	"official":                               nil,
	"awesome":                                nil,
	"super":                                  nil,
	"jeux vidéo":                             nil,
	"Hangouts On Air":                        nil,
	"build":                                  nil,
	"amazing":                                nil,
	"scary":                                  nil,
	"cool":                                   nil,
	"no commentary":                          nil,
	"fight":                                  nil,
	"pewdiepie":                              nil,
	"India":                                  nil,
	"livestream":                             nil,
	"festival":                               nil,
	"Live":                                   nil,
	"shooter":                                nil,
	"influencer":                             nil,
	"power":                                  nil,
	"black":                                  nil,
	"liquid":                                 nil,
	"reaction":                               nil,
	"mobile":                                 nil,
	"vlogs":                                  nil,
	"voice":                                  nil,
	"fails":                                  nil,
	"deep":                                   nil,
	"crazy":                                  nil,
	"rants":                                  nil,
	"like":                                   nil,
	"speed":                                  nil,
	"fights":                                 nil,
	"Fun":                                    nil,
	"friends":                                nil,
	"women":                                  nil,
	"old":                                    nil,
	"fireworks":                              nil,
	"compilation":                            nil,
	"gopro":                                  nil,
	"energy":                                 nil,
	"navidad":                                nil,
	"quality":                                nil,
	"farm":                                   nil,
	"Commentary":                             nil,
	"Challenges":                             nil,
	"alien":                                  nil,
	"house party":                            nil,
	"house flipper":                          nil,
	"kids":                                   nil,
	"king":                                   nil,
	"beta":                                   nil,
	"team":                                   nil,
	"Champion":                               nil,
	"vlogger":                                nil,
	"time":                                   nil,
	"street":                                 nil,
	"bollywood":                              nil,
	"death voice":                            nil,
	"death noise":                            nil,
	"moments":                                nil,
	"injured":                                nil,
	"wounded":                                nil,
	"terror":                                 nil,
	"party":                                  nil,
	"craft":                                  nil,
	"english":                                nil,
	"city":                                   nil,
	"dark":                                   nil,
	"coplanet":                               nil,
	"solo":                                   nil,
	"fighting":                               nil,
	"dead":                                   nil,
	"alpha":                                  nil,
	"blog":                                   nil,
	"colorful":                               nil,
	"futuristic":                             nil,
	"react":                                  nil,
	"gay":                                    nil,
	"raid":                                   nil,
	"mmr":                                    nil,
	"high":                                   nil,
	"outrageous":                             nil,
	"support":                                nil,
	"relationships":                          nil,
	"base":                                   nil,
	"girls":                                  nil,
	"sex":                                    nil,
	"girl":                                   nil,
	"sexy":                                   nil,
}
var mapAndReplace = map[string]string{
	"nfl":                            Sports,
	"Minecraft (Award-Winning Work)": Gaming,
	"minecraft survival":             Gaming,
	"modded minecraft":               Gaming,
	"minecraft movie":                Gaming,
	"minecraft videos":               Gaming,
}

var mapAndKeep = map[string]string{
	"dance":                               Art,
	"design":                              Art,
	"fashion":                             Art,
	"creative hairstyles":                 Art,
	"colorful hair":                       Art,
	"cool long hair":                      Art,
	"cartoon":                             Art,
	"comic":                               Art,
	"comics":                              Art,
	"beauty":                              Art,
	"car":                                 Automotive,
	"CARS":                                Automotive,
	"4x4":                                 Automotive,
	"AUTOMOBILE":                          Automotive,
	"autos":                               Automotive,
	"Carros":                              Automotive,
	"Suv":                                 Automotive,
	"TRUCK":                               Automotive,
	"Garage":                              Automotive,
	"auto":                                Automotive,
	"crash":                               Automotive,
	"driving":                             Automotive,
	"cars":                                Automotive,
	"race":                                Automotive,
	"Bmw":                                 Automotive,
	"vehicle":                             Automotive,
	"Benz":                                Automotive,
	"Auto Show (Event)":                   Automotive,
	"Mercedes":                            Automotive,
	"engine":                              Automotive,
	"mercedes":                            Automotive,
	"motorcycle":                          Automotive,
	"porsche":                             Automotive,
	"Bus":                                 Automotive,
	"jeep":                                Automotive,
	"secular talk":                        Beliefs,
	"atheist":                             Beliefs,
	"atheism":                             Beliefs,
	"agnostic":                            Beliefs,
	"freedom":                             Beliefs,
	"secular":                             Beliefs,
	"religion":                            Beliefs,
	"liberty":                             Beliefs,
	"christian":                           Beliefs,
	"god":                                 Beliefs,
	"libertarian":                         Beliefs,
	"guru":                                Beliefs,
	"muslim":                              Beliefs,
	"voluntarism":                         Beliefs,
	"yogi":                                Beliefs,
	"mystic":                              Beliefs,
	"bible":                               Beliefs,
	"jesus":                               Beliefs,
	"anarchism":                           Beliefs,
	"christianity":                        Beliefs,
	"anarchy":                             Beliefs,
	"voluntaryist":                        Beliefs,
	"activism":                            Beliefs,
	"hindu":                               Beliefs,
	"peace":                               Beliefs,
	"love":                                Beliefs,
	"death":                               Beliefs,
	"christmas":                           Beliefs,
	"lord":                                Beliefs,
	"bitcoin":                             Blockchain,
	"cryptocurrency":                      Blockchain,
	"crypto":                              Blockchain,
	"ethereum":                            Blockchain,
	"btc":                                 Blockchain,
	"airdrop":                             Blockchain,
	"litecoin":                            Blockchain,
	"eth":                                 Blockchain,
	"mining":                              Blockchain,
	"bitcoin news":                        Blockchain,
	"ico":                                 Blockchain,
	"crypto news":                         Blockchain,
	"token":                               Blockchain,
	"token free":                          Blockchain,
	"bitcoin price":                       Blockchain,
	"altcoins":                            Blockchain,
	"cryptocurrency news":                 Blockchain,
	"altcoin":                             Blockchain,
	"coin":                                Blockchain,
	"ripple":                              Blockchain,
	"free bitcoin":                        Blockchain,
	"ltc":                                 Blockchain,
	"dash":                                Blockchain,
	"eos":                                 Blockchain,
	"steemit":                             Blockchain,
	"coinbase":                            Blockchain,
	"cryptocurrencies":                    Blockchain,
	"money":                               Economics,
	"economy":                             Economics,
	"gold":                                Economics,
	"federal reserve":                     Economics,
	"market":                              Economics,
	"investing":                           Economics,
	"dollar":                              Economics,
	"monetary reform":                     Economics,
	"economic":                            Economics,
	"recession":                           Economics,
	"trading":                             Economics,
	"finance":                             Economics,
	"currency":                            Economics,
	"business":                            Economics,
	"health":                              Food,
	"vegan":                               Food,
	"fruits":                              Food,
	"vegán":                               Food,
	"food holidays":                       Food,
	"comedy":                              Funny,
	"fun":                                 Funny,
	"Funny":                               Funny,
	"hilarious":                           Funny,
	"lol":                                 Funny,
	"satire":                              Funny,
	"humor":                               Funny,
	"funny moments":                       Funny,
	"Comedy":                              Funny,
	"parody":                              Funny,
	"funny video":                         Funny,
	"silly":                               Funny,
	"humour":                              Funny,
	"Satire":                              Funny,
	"gameplay":                            Gaming,
	"games":                               Gaming,
	"game":                                Gaming,
	"PlayStation 4":                       Gaming,
	"Sony Interactive Entertainment":      Gaming,
	"walkthrough":                         Gaming,
	"playthrough":                         Gaming,
	"#PS4Live":                            Gaming,
	"let's play":                          Gaming,
	"play":                                Gaming,
	"lets play":                           Gaming,
	"minecraft":                           Gaming,
	"twitch":                              Gaming,
	"Video Game (Industry)":               Gaming,
	"ps4":                                 Gaming,
	"#PS4share":                           Gaming,
	"xbox":                                Gaming,
	"Gaming":                              Gaming,
	"video game":                          Gaming,
	"playstation":                         Gaming,
	"xbox one":                            Gaming,
	"steam":                               Gaming,
	"fortnite":                            Gaming,
	"playstation 4":                       Gaming,
	"video games":                         Gaming,
	"lets":                                Gaming,
	"nintendo":                            Gaming,
	"ps3":                                 Gaming,
	"fps":                                 Gaming,
	"rpg":                                 Gaming,
	"video game (industry)":               Gaming,
	"multiplayer":                         Gaming,
	"let's":                               Gaming,
	"Fortnite":                            Gaming,
	"dota 2":                              Gaming,
	"xbox 360":                            Gaming,
	"Sony Computer Entertainment":         Gaming,
	"pc games":                            Gaming,
	"Gamer":                               Gaming,
	"call of duty":                        Gaming,
	"pokemon":                             Gaming,
	"League":                              Gaming,
	"Let's Play":                          Gaming,
	"Let's":                               Gaming,
	"league of legends":                   Gaming,
	"League Of Legends (Video Game)":      Gaming,
	"cod":                                 Gaming,
	"pubg":                                Gaming,
	"Xbox":                                Gaming,
	"pvp":                                 Gaming,
	"videogame":                           Gaming,
	"dota":                                Gaming,
	"Games":                               Gaming,
	"let's play fr":                       Gaming,
	"mario":                               Gaming,
	"pc game":                             Gaming,
	"PS4":                                 Gaming,
	"let":                                 Gaming,
	"fallout 4":                           Gaming,
	"Shooter Game (Media Genre)":          Gaming,
	"Playthrough":                         Gaming,
	"gamer":                               Gaming,
	"wii":                                 Gaming,
	"playing":                             Gaming,
	"computer game games":                 Gaming,
	"Gameplay":                            Gaming,
	"arcade":                              Gaming,
	"Video Game Culture":                  Gaming,
	"Xbox 360 (Video Game Platform)":      Gaming,
	"RPG":                                 Gaming,
	"Game":                                Gaming,
	"gta":                                 Gaming,
	"let’s play":                          Gaming,
	"Minecraft":                           Gaming,
	"skyrim":                              Gaming,
	"Action-adventure Game (Media Genre)": Gaming,
	"sony interactive entertainment":      Gaming,
	"dlc":                                 Gaming,
	"xbox360":                             Gaming,
	"zelda":                               Gaming,
	"Steam":                               Gaming,
	"capcom":                              Gaming,
	"fortnite battle royale":              Gaming,
	"singleplayer":                        Gaming,
	"pacman":                              Gaming,
	"gta 5":                               Gaming,
	"Grand Theft Auto V":                  Gaming,
	"valve":                               Gaming,
	"Massively Multiplayer Online Role-playing Game (Video Game Genre)": Gaming,
	"#gaming":                               Gaming,
	"halo":                                  Gaming,
	"computer games":                        Gaming,
	"nintendo switch":                       Gaming,
	"3d games":                              Gaming,
	"MOBA":                                  Gaming,
	"Ps2":                                   Gaming,
	"Role-playing Video Game (Media Genre)": Gaming,
	"supercell":                             Gaming,
	"dota2":                                 Gaming,
	"sims":                                  Gaming,
	"pc gaming":                             Gaming,
	"Playstation 4":                         Gaming,
	"battle royale":                         Gaming,
	"rpg games":                             Gaming,
	"sims 4":                                Gaming,
	"roblox":                                Gaming,
	"Mw3":                                   Gaming,
	"far cry 5":                             Gaming,
	"squad gameplay":                        Gaming,
	"tf2":                                   Gaming,
	"Ps3":                                   Gaming,
	"Resident Evil":                         Gaming,
	"indie game":                            Gaming,
	"overwatch":                             Gaming,
	"brawl":                                 Gaming,
	"Call of Duty®: Black Ops III":          Gaming,
	"console":                               Gaming,
	"mugen":                                 Gaming,
	"Play":                                  Gaming,
	"Mass effect":                           Gaming,
	"ubisoft":                               Gaming,
	"Minecraft: PlayStation®4 Edition":      Gaming,
	"rts":                                   Gaming,
	"mmorpg":                                Gaming,
	"first person shooter":                  Gaming,
	"Action Role-playing Game (Video Game Genre)": Gaming,
	"Role-playing Game (Game Genre)":              Gaming,
	"sonic":                                       Gaming,
	"videogames":                                  Gaming,
	"Simulator":                                   Gaming,
	"level":                                       Gaming,
	"sims 3":                                      Gaming,
	"esports":                                     Gaming,
	"Minecraft (Video Game)":                      Gaming,
	"simulator":                                   Gaming,
	"horrible gamers":                             Gaming,
	"moba":                                        Gaming,
	"the game":                                    Gaming,
	"link":                                        Gaming,
	"Game Reviews":                                Gaming,
	"sims 5":                                      Gaming,
	"snk":                                         Gaming,
	"online games":                                Gaming,
	"squad game":                                  Gaming,
	"switch":                                      Gaming,
	"Lets Play":                                   Gaming,
	"portal":                                      Gaming,
	"boss":                                        Gaming,
	"mod":                                         Gaming,
	"strategy":                                    Gaming,
	"stream":                                      Gaming,
	"Stream":                                      Gaming,
	"galaxy":                                      Gaming,
	"tutorial":                                    Learning,
	"how to":                                      Learning,
	"Education":                                   Learning,
	"Educational":                                 Learning,
	"how":                                         Learning,
	"SALMAN KHAN":                                 Learning,
	"education":                                   Learning,
	"help":                                        Learning,
	"lessons":                                     Learning,
	"online learning":                             Learning,
	"diy":                                         Learning,
	"school":                                      Learning,
	"how-to":                                      Learning,
	"howto":                                       Learning,
	"advice":                                      Learning,
	"history":                                     Learning,
	"inspirational":                               Learning,
	"drum and bass":                               Music,
	"bass":                                        Music,
	"dubstep":                                     Music,
	"song":                                        Music,
	"rap":                                         Music,
	"remix":                                       Music,
	"drum":                                        Music,
	"house":                                       Music,
	"drum bass":                                   Music,
	"darkstep":                                    Music,
	"guitar":                                      Music,
	"drumstep":                                    Music,
	"techstep":                                    Music,
	"metal":                                       Music,
	"dj":                                          Music,
	"rock":                                        Music,
	"New Music":                                   Music,
	"hip hop":                                     Music,
	"cover":                                       Music,
	"instrumental":                                Music,
	"electronic":                                  Music,
	"alternative":                                 Music,
	"space":                                       Nature,
	"plants":                                      Nature,
	"trees":                                       Nature,
	"eggs":                                        Nature,
	"flowers":                                     Nature,
	"beach":                                       Nature,
	"rainbow":                                     Nature,
	"water":                                       Nature,
	"animals":                                     Nature,
	"floral":                                      Nature,
	"gardening":                                   Nature,
	"garden":                                      Nature,
	"survival":                                    Nature,
	"world":                                       Nature,
	"dog":                                         Nature,
	"travel":                                      Nature,
	"rv":                                          Nature,
	"Survival":                                    Nature,
	"outdoor":                                     Nature,
	"full time rving":                             Nature,
	"rv park":                                     Nature,
	"travel trailer":                              Nature,
	"Environment":                                 Nature,
	"News":                                        News,
	"politics":                                    News,
	"democrat":                                    News,
	"liberal":                                     News,
	"progressive":                                 News,
	"government":                                  News,
	"republican":                                  News,
	"conservative":                                News,
	"commentary":                                  News,
	"political":                                   News,
	"CNN":                                         News,
	"cbs":                                         News,
	"MSNBC":                                       News,
	"Fox news":                                    News,
	"fox":                                         News,
	"nbc":                                         News,
	"POLITICS":                                    News,
	"News & Politics":                             News,
	"senate":                                      News,
	"congress":                                    News,
	"house of representatives":                    News,
	"video news":                                  News,
	"animated news":                               News,
	"donald trump":                                News,
	"COMO":                                        News,
	"TRUMP":                                       News,
	"PUTIN":                                       News,
	"news radio":                                  News,
	"Hillary Clinton":                             News,
	"progressive talk":                            News,
	"trump":                                       News,
	"barack obama":                                News,
	"Donald Trump":                                News,
	"newscast":                                    News,
	"racism":                                      News,
	"war":                                         News,
	"horror":                                      PopCulture,
	"zombies":                                     PopCulture,
	"Next Media Animation":                        PopCulture,
	"adventure":                                   PopCulture,
	"epic":                                        PopCulture,
	"anime":                                       PopCulture,
	"trailer":                                     PopCulture,
	"reviews":                                     PopCulture,
	"movie":                                       PopCulture,
	"indie":                                       PopCulture,
	"pro":                                         PopCulture,
	"animation":                                   PopCulture,
	"zombie":                                      PopCulture,
	"star":                                        PopCulture,
	"film":                                        PopCulture,
	"magic":                                       PopCulture,
	"ninja":                                       PopCulture,
	"top 10":                                      PopCulture,
	"wwe":                                         PopCulture,
	"loot":                                        PopCulture,
	"marvel":                                      PopCulture,
	"manga":                                       PopCulture,
	"puzzle":                                      PopCulture,
	"hero":                                        PopCulture,
	"retro":                                       PopCulture,
	"disney":                                      PopCulture,
	"dc":                                          PopCulture,
	"next animation studio":                       PopCulture,
	"Next Animation Studio":                       PopCulture,
	"cosplay":                                     PopCulture,
	"dragoncon":                                   PopCulture,
	"comiccon":                                    PopCulture,
	"stories":                                     PopCulture,
	"unboxing":                                    PopCulture,
	"fail":                                        PopCulture,
	"dragon":                                      PopCulture,
	"Reaction":                                    PopCulture,
	"meme":                                        PopCulture,
	"family friendly":                             PopCulture,
	"random":                                      PopCulture,
	"vlogging":                                    PopCulture,
	"React":                                       PopCulture,
	"Trailer":                                     PopCulture,
	"REACTION":                                    PopCulture,
	"toys":                                        PopCulture,
	"reacts":                                      PopCulture,
	"cute":                                        PopCulture,
	"weed":                                        PopCulture,
	"drunkfx":                                     PopCulture,
	"happy":                                       PopCulture,
	"Anime":                                       PopCulture,
	"family":                                      PopCulture,
	"memes":                                       PopCulture,
	"wtf":                                         PopCulture,
	"Sport":                                       Sports,
	"racing":                                      Sports,
	"sport":                                       Sports,
	"training":                                    Sports,
	"football":                                    Sports,
	"pc":                                          Technology,
	"android":                                     Technology,
	"computer":                                    Technology,
	"online":                                      Technology,
	"mods":                                        Technology,
	"tech":                                        Technology,
	"ios":                                         Technology,
	"linux":                                       Technology,
	"sony":                                        Technology,
	"iphone":                                      Technology,
	"PC":                                          Technology,
	"ram":                                         Technology,
	"samsung":                                     Technology,
	"software":                                    Technology,
	"windows":                                     Technology,
	"programming":                                 Technology,
	"simulation":                                  Technology,
	"facebook":                                    Technology,
	"desktop":                                     Technology,
	"install":                                     Technology,
	"microsoft":                                   Technology,
	"twitter":                                     Technology,
	"Android":                                     Technology,
	"Mobile":                                      Technology,
	"apple":                                       Technology,
	"iOS":                                         Technology,
	"server":                                      Technology,
	"Nvidia":                                      Technology,
	"open source":                                 Technology,
	"Apple":                                       Technology,
	"apps":                                        Technology,
	"laptop":                                      Technology,
	"podcast":                                     Technology,
	"hack":                                        Technology,
	"guns":                                        Weapons,
	"shooting":                                    Weapons,
	"trophy":                                      Weapons,
	"combat":                                      Weapons,
	"fire":                                        Weapons,
	"gun":                                         Weapons,
	"tactical":                                    Weapons,
	"firearms":                                    Weapons,
	"rocket":                                      Weapons,
	"sniper":                                      Weapons,
	"knife":                                       Weapons,
	"trap":                                        Weapons,
	"assault":                                     Weapons,
}
