package tagsManager

const (
	Gaming     = "gaming"
	Blockchain = "blockchain"
	News       = "news"
	Learning   = "learning"
	Funny      = "funny"
	Technology = "technology"
	Automotive = "automotive"
	Economics  = "economics"
	Sports     = "sports"
	Food       = "food"
	Science    = "science"
	Fitness    = "fitness"
	Art        = "art"
	Nature     = "nature"
)

func SanitizeTags(tags []string) []string {
	ts := &tagsSanitizer{
		Unsanitized: tags,
	}
	ts.init()
	ts.cleanup()
	ts.replace()
	ts.add()

	sanitizedTags := make([]string, len(ts.Sanitized))
	index := 0
	for t := range ts.Sanitized {
		sanitizedTags[index] = t
		index++
	}
	return sanitizedTags
}

type tagsSanitizer struct {
	Unsanitized []string
	Sanitized   map[string]bool
}

func (ts *tagsSanitizer) init() {
	if len(ts.Sanitized) == 0 {
		ts.Sanitized = make(map[string]bool, len(ts.Unsanitized)+14)
	}
}

func (ts *tagsSanitizer) cleanup() {
	for _, t := range ts.Unsanitized {
		_, ok := tagsToSkip[t]
		if !ok {
			ts.Sanitized[t] = true
		}
	}
}

func (ts *tagsSanitizer) replace() {
	for _, t := range ts.Unsanitized {
		match, filterMatch := mapAndReplace[t]
		if filterMatch {
			delete(ts.Sanitized, t)
			ts.Sanitized[match] = true
		}
	}
}

func (ts *tagsSanitizer) add() {
	for _, t := range ts.Unsanitized {
		match, filterMatch := mapAndKeep[t]
		if filterMatch {
			ts.Sanitized[match] = true
			ts.Sanitized[t] = true
		}
	}
}

var tagsToSkip = map[string]*struct{}{
	"video":                                  nil,
	"review":                                 nil,
	"youtube":                                nil,
	"david packman":                          nil,
	"2018":                                   nil,
	"new":                                    nil,
	"the":                                    nil,
	"music":                                  nil,
	"hd":                                     nil,
	"talk":                                   nil,
	"entertainment":                          nil,
	"Radio":                                  nil,
	"2017":                                   nil,
	"live":                                   nil,
	"free":                                   nil,
	"america":                                nil,
	"of":                                     nil,
	"david pakman":                           nil,
	"dave pacman":                            nil,
	"pakman":                                 nil,
	"davidpakman.com":                        nil,
	"tdps":                                   nil,
	"1080p":                                  nil,
	"united":                                 nil,
	"david pakman show":                      nil,
	"states":                                 nil,
	"europe":                                 nil,
	"tomonews":                               nil,
	"Tomonews":                               nil,
	"2016":                                   nil,
	"eeuu":                                   nil,
	"REVIEW":                                 nil,
	"Launch":                                 nil,
	"taiwanese animators":                    nil,
	"best":                                   nil,
	"TURBO":                                  nil,
	"television":                             nil,
	"gt":                                     nil,
	"USA":                                    nil,
	"GPS":                                    nil,
	"PREMIERE":                               nil,
	"guide":                                  nil,
	"scoope":                                 nil,
	"US":                                     nil,
	"nma":                                    nil,
	"Nma":                                    nil,
	"to":                                     nil,
	"auto imagen":                            nil,
	"tips":                                   nil,
	"action":                                 nil,
	"download":                               nil,
	"david pacman":                           nil,
	"taiwanese animation":                    nil,
	"Taiwanese animation":                    nil,
	"YouTube Editor":                         nil,
	"Tomo news":                              nil,
	"replay":                                 nil,
	"update":                                 nil,
	"battle":                                 nil,
	"2019":                                   nil,
	"story":                                  nil,
	"one":                                    nil,
	"spreaker":                               nil,
	"Jay's":                                  nil,
	"episode":                                nil,
	"for":                                    nil,
	"SHAREfactory™":                          nil,
	"#hangoutsonair":                         nil,
	"#hoa":                                   nil,
	"vs":                                     nil,
	"bob":                                    nil,
	"dnb portal":                             nil,
	"instagram":                              nil,
	"challenge":                              nil,
	"eatmydiction1":                          nil,
	"usa":                                    nil,
	"français":                               nil,
	"live stream":                            nil,
	"top":                                    nil,
	"fr":                                     nil,
	"fanta":                                  nil,
	"HD":                                     nil,
	"and":                                    nil,
	"foto":                                   nil,
	"no":                                     nil,
	"720p":                                   nil,
	"up":                                     nil,
	"radio":                                  nil,
	"david":                                  nil,
	"russia":                                 nil,
	"ytquality=high":                         nil,
	"part":                                   nil,
	"bollywood tashan":                       nil,
	"bounty":                                 nil,
	"dnb":                                    nil,
	"highlights":                             nil,
	"thefantasio974":                         nil,
	"great":                                  nil,
	"man":                                    nil,
	"replica":                                nil,
	"red":                                    nil,
	"chiara ferragni":                        nil,
	"in":                                     nil,
	"bob lennon":                             nil,
	"series":                                 nil,
	"life":                                   nil,
	"first":                                  nil,
	"dnbportal":                              nil,
	"fantabobgames":                          nil,
	"segui":                                  nil,
	"lennon":                                 nil,
	"neurofunk":                              nil,
	"on":                                     nil,
	"kag3":                                   nil,
	"2015":                                   nil,
	"ITA":                                    nil,
	"gamerworf":                              nil,
	"chickens":                               nil,
	"uct-wqktykk1_70u4bb4k4lq":               nil,
	"beard":                                  nil,
	"videos":                                 nil,
	"nidge":                                  nil,
	"bill still":                             nil,
	"nickatnyte":                             nil,
	"прохождение":                            nil,
	"minimal":                                nil,
	"clash":                                  nil,
	"trofeo":                                 nil,
	"attack":                                 nil,
	"test":                                   nil,
	"DFX":                                    nil,
	"india":                                  nil,
	"police":                                 nil,
	"campaign":                               nil,
	"tricks":                                 nil,
	"depression":                             nil,
	"unique":                                 nil,
	"Bharat":                                 nil,
	"imagen":                                 nil,
	"LanceScurv":                             nil,
	"us":                                     nil,
	"google":                                 nil,
	"defense":                                nil,
	"gameplay fr":                            nil,
	"giveaway":                               nil,
	"hot":                                    nil,
	"Interior":                               nil,
	"show":                                   nil,
	"YouTube Capture":                        nil,
	"jump":                                   nil,
	"2014":                                   nil,
	"thailand":                               nil,
	"santa":                                  nil,
	"ultimate":                               nil,
	"deutsch":                                nil,
	"mission":                                nil,
	"The Lancescurv Show":                    nil,
	"Legends":                                nil,
	"modi":                                   nil,
	"noise":                                  nil,
	"Texas":                                  nil,
	"china":                                  nil,
	"Scurv":                                  nil,
	"gift":                                   nil,
	"sikh":                                   nil,
	"night":                                  nil,
	"Episode":                                nil,
	"good":                                   nil,
	"plus":                                   nil,
	"szekelyvegan":                           nil,
	"székelyvegán":                           nil,
	"szekely":                                nil,
	"игра":                                   nil,
	"is":                                     nil,
	"székely vegán":                          nil,
	"john sonmez":                            nil,
	"jew":                                    nil,
	"magyar vlogger":                         nil,
	"magyar vlog":                            nil,
	"hungarian vlog":                         nil,
	"baba":                                   nil,
	"montage":                                nil,
	"New":                                    nil,
	"squad":                                  nil,
	"german":                                 nil,
	"amerika":                                nil,
	"full":                                   nil,
	"sri":                                    nil,
	"kristomaster4":                          nil,
	"narendra":                               nil,
	"sant":                                   nil,
	"adityanath":                             nil,
	"sadhguru":                               nil,
	"ped":                                    nil,
	"Sadhu":                                  nil,
	"Shyam":                                  nil,
	"dharm":                                  nil,
	"babas":                                  nil,
	"gaay":                                   nil,
	"Pradesh":                                nil,
	"Raebareli":                              nil,
	"waale":                                  nil,
	"Uttar":                                  nil,
	"Bandar":                                 nil,
	"kutta":                                  nil,
	"bakri":                                  nil,
	"aughad":                                 nil,
	"suar":                                   nil,
	"jaanwar":                                nil,
	"tona":                                   nil,
	"bhawreshwara":                           nil,
	"vaanar":                                 nil,
	"bhagwa":                                 nil,
	"prakriti":                               nil,
	"samaj":                                  nil,
	"totka":                                  nil,
	"bhoj":                                   nil,
	"dave":                                   nil,
	"vulcanhdgaming":                         nil,
	"fast":                                   nil,
	"moon":                                   nil,
	"scene":                                  nil,
	"tv":                                     nil,
	"2":                                      nil,
	"fighter":                                nil,
	"NEW":                                    nil,
	"jeux":                                   nil,
	"игры":                                   nil,
	"tanyázás":                               nil,
	"obiettivo":                              nil,
	"csgo":                                   nil,
	"The guy From Pittsburgh":                nil,
	"blue":                                   nil,
	"youtuber":                               nil,
	"clash royale":                           nil,
	"SHOW":                                   nil,
	"johnsp69":                               nil,
	"japan":                                  nil,
	"YouTube":                                nil,
	"The David Pakman Show":                  nil,
	"thecreativeone":                         nil,
	"Youtube":                                nil,
	"classic":                                nil,
	"Talk Radio":                             nil,
	"white":                                  nil,
	"летсплей":                               nil,
	"clash of clans":                         nil,
	"Industry (Organization Sector)":         nil,
	"difranco":                               nil,
	"custom":                                 nil,
	"прохождение игры":                       nil,
	"progressive podcast":                    nil,
	"george Senda":                           nil,
	"360":                                    nil,
	"betv":                                   nil,
	"gamingoncaffeine":                       nil,
	"Drive":                                  nil,
	"Africa":                                 nil,
	"progressive news":                       nil,
	"full hd":                                nil,
	"Asia":                                   nil,
	"liberal news":                           nil,
	"packman":                                nil,
	"hdtv":                                   nil,
	"Entertainment":                          nil,
	"Simple Programmer":                      nil,
	"indonesia":                              nil,
	"karmakut":                               nil,
	"gorthemoviegod":                         nil,
	"Lance scurvin":                          nil,
	"silver":                                 nil,
	"clans":                                  nil,
	"игры для мальчиков":                     nil,
	"игры для девочек":                       nil,
	"blackpeace72":                           nil,
	"multicolored":                           nil,
	"intro":                                  nil,
	"creative beard":                         nil,
	"cyber locks":                            nil,
	"uniqornaments":                          nil,
	"daily holidays":                         nil,
	"daily celebration":                      nil,
	"holiday everyday":                       nil,
	"3d":                                     nil,
	"lp":                                     nil,
	"interview":                              nil,
	"Heroes":                                 nil,
	"maskedmage":                             nil,
	"рпг":                                    nil,
	"north":                                  nil,
	"road":                                   nil,
	"monster":                                nil,
	"de":                                     nil,
	"mode":                                   nil,
	"podcastradio":                           nil,
	"Man":                                    nil,
	"preview":                                nil,
	"rage":                                   nil,
	"map":                                    nil,
	"Pittsburgh pa":                          nil,
	"david di franco":                        nil,
	"win":                                    nil,
	"junior senior":                          nil,
	"demo":                                   nil,
	"paul":                                   nil,
	"simpleprogrammer.com":                   nil,
	"2013":                                   nil,
	"green":                                  nil,
	"la":                                     nil,
	"london":                                 nil,
	"adam":                                   nil,
	"jnrsnrgaming":                           nil,
	"jnrsnr":                                 nil,
	"TRUE":                                   nil,
	"junior senior gaming":                   nil,
	"the kag3 gaming":                        nil,
	"sonny daniel":                           nil,
	"atlanta":                                nil,
	"wordofgod":                              nil,
	"2012":                                   nil,
	"Katrina kaif":                           nil,
	"English":                                nil,
	"Addon":                                  nil,
	"High":                                   nil,
	"To":                                     nil,
	"willie":                                 nil,
	"it":                                     nil,
	"trolling":                               nil,
	"Bollywood news":                         nil,
	"willie pelissier":                       nil,
	"canada":                                 nil,
	"productions":                            nil,
	"iMovie":                                 nil,
	"channel":                                nil,
	"total":                                  nil,
	"trick":                                  nil,
	"the kag3":                               nil,
	"Scurvin":                                nil,
	"Free":                                   nil,
	"make":                                   nil,
	"The":                                    nil,
	"ops":                                    nil,
	"trevor":                                 nil,
	"kevin":                                  nil,
	"life is strange":                        nil,
	"you":                                    nil,
	"kokesh":                                 nil,
	"the brotherhood of gaming":              nil,
	"Martinez ca":                            nil,
	"real":                                   nil,
	"เกม":                                    nil,
	"sonny daniel vlogs":                     nil,
	"China":                                  nil,
	"African American":                       nil,
	"Slime":                                  nil,
	"America":                                nil,
	"price":                                  nil,
	"michigan":                               nil,
	"call":                                   nil,
	"truetotalempireinc":                     nil,
	"Akshay Kumar":                           nil,
	"Shield":                                 nil,
	"aventure":                               nil,
	"until dawn":                             nil,
	"camera":                                 nil,
	"florida":                                nil,
	"with":                                   nil,
	"battlefield":                            nil,
	"joe":                                    nil,
	"tom":                                    nil,
	"Atmospheric":                            nil,
	"squad ops":                              nil,
	"overview":                               nil,
	"fist":                                   nil,
	"clan":                                   nil,
	"guy":                                    nil,
	"sonnydaniel":                            nil,
	"Voice Over":                             nil,
	"Test":                                   nil,
	"HouseParty":                             nil,
	"ending":                                 nil,
	"my":                                     nil,
	"garena":                                 nil,
	"kag3 entertainment":                     nil,
	"{5859dfec-026f-46ba-bea0-02bf43aa1a6f}": nil,
	"shahrukh Khan":                          nil,
	"Opening":                                nil,
	"erik":                                   nil,
	"part 1":                                 nil,
	"UK":                                     nil,
	"dean":                                   nil,
	"hcg":                                    nil,
	"4k":                                     nil,
	"cheat":                                  nil,
}
var mapAndReplace = map[string]string{
	"nfl":                            Sports,
	"Minecraft (Award-Winning Work)": Gaming,
	"minecraft survival":             Gaming,
	"modded minecraft":               Gaming,
	"minecraft movie":                Gaming,
	"minecraft videos":               Gaming,
}

var mapAndKeep = map[string]string{
	"gameplay":                            Gaming,
	"games":                               Gaming,
	"News":                                News,
	"game":                                Gaming,
	"politics":                            News,
	"PlayStation 4":                       Gaming,
	"Sony Interactive Entertainment":      Gaming,
	"walkthrough":                         Gaming,
	"pc":                                  Technology,
	"playthrough":                         Gaming,
	"#PS4Live":                            Gaming,
	"let's play":                          Gaming,
	"democrat":                            News,
	"liberal":                             News,
	"progressive":                         News,
	"government":                          News,
	"play":                                Gaming,
	"republican":                          News,
	"conservative":                        News,
	"commentary":                          News,
	"political":                           News,
	"CNN":                                 News,
	"tutorial":                            Learning,
	"cbs":                                 News,
	"lets play":                           Gaming,
	"MSNBC":                               News,
	"bitcoin":                             Blockchain,
	"minecraft":                           Gaming,
	"twitch":                              Gaming,
	"Video Game (Industry)":               Gaming,
	"ps4":                                 Gaming,
	"#PS4share":                           Gaming,
	"how to":                              Learning,
	"Fox news":                            News,
	"fox":                                 News,
	"xbox":                                Gaming,
	"nbc":                                 News,
	"Gaming":                              Gaming,
	"comedy":                              Funny,
	"video game":                          Gaming,
	"car":                                 Automotive,
	"Education":                           Learning,
	"POLITICS":                            News,
	"Educational":                         Learning,
	"cryptocurrency":                      Blockchain,
	"News & Politics":                     News,
	"fun":                                 Funny,
	"playstation":                         Gaming,
	"CARS":                                Automotive,
	"xbox one":                            Gaming,
	"senate":                              News,
	"steam":                               Gaming,
	"4x4":                                 Automotive,
	"AUTOMOBILE":                          Automotive,
	"fortnite":                            Gaming,
	"autos":                               Automotive,
	"Sport":                               Sports,
	"crypto":                              Blockchain,
	"Carros":                              Automotive,
	"ethereum":                            Blockchain,
	"Suv":                                 Automotive,
	"playstation 4":                       Gaming,
	"TRUCK":                               Automotive,
	"video games":                         Gaming,
	"Funny":                               Funny,
	"Garage":                              Automotive,
	"congress":                            News,
	"lets":                                Gaming,
	"nintendo":                            Gaming,
	"ps3":                                 Gaming,
	"auto":                                Automotive,
	"house of representatives":            News,
	"fps":                                 Gaming,
	"rpg":                                 Gaming,
	"btc":                                 Blockchain,
	"video game (industry)":               Gaming,
	"multiplayer":                         Gaming,
	"video news":                          News,
	"animated news":                       News,
	"android":                             Technology,
	"computer":                            Technology,
	"how":                                 Learning,
	"let's":                               Gaming,
	"donald trump":                        News,
	"Fortnite":                            Gaming,
	"COMO":                                News,
	"online":                              Technology,
	"TRUMP":                               News,
	"mods":                                Technology,
	"tech":                                Technology,
	"hilarious":                           Funny,
	"dota 2":                              Gaming,
	"crash":                               Automotive,
	"PUTIN":                               News,
	"dance":                               Art,
	"money":                               Economics,
	"news radio":                          News,
	"lol":                                 Funny,
	"xbox 360":                            Gaming,
	"SALMAN KHAN":                         Learning,
	"airdrop":                             Blockchain,
	"litecoin":                            Blockchain,
	"Sony Computer Entertainment":         Gaming,
	"pc games":                            Gaming,
	"eth":                                 Blockchain,
	"mining":                              Blockchain,
	"ios":                                 Technology,
	"linux":                               Technology,
	"sony":                                Technology,
	"space":                               Nature,
	"iphone":                              Technology,
	"education":                           Learning,
	"Gamer":                               Gaming,
	"bitcoin news":                        Blockchain,
	"call of duty":                        Gaming,
	"pokemon":                             Gaming,
	"League":                              Gaming,
	"Let's Play":                          Gaming,
	"Let's":                               Gaming,
	"league of legends":                   Gaming,
	"League Of Legends (Video Game)":      Gaming,
	"economy":                             Economics,
	"cod":                                 Gaming,
	"ico":                                 Blockchain,
	"pubg":                                Gaming,
	"gold":                                Economics,
	"Xbox":                                Gaming,
	"pvp":                                 Gaming,
	"videogame":                           Gaming,
	"vegan":                               Food,
	"dota":                                Gaming,
	"Games":                               Gaming,
	"let's play fr":                       Gaming,
	"satire":                              Funny,
	"mario":                               Gaming,
	"pc game":                             Gaming,
	"help":                                Learning,
	"PS4":                                 Gaming,
	"crypto news":                         Blockchain,
	"humor":                               Funny,
	"let":                                 Gaming,
	"fallout 4":                           Gaming,
	"Shooter Game (Media Genre)":          Gaming,
	"funny moments":                       Funny,
	"Comedy":                              Funny,
	"Playthrough":                         Gaming,
	"gamer":                               Gaming,
	"wii":                                 Gaming,
	"playing":                             Gaming,
	"PC":                                  Technology,
	"computer game games":                 Gaming,
	"Gameplay":                            Gaming,
	"arcade":                              Gaming,
	"token":                               Blockchain,
	"federal reserve":                     Economics,
	"Video Game Culture":                  Gaming,
	"driving":                             Automotive,
	"plants":                              Nature,
	"trees":                               Nature,
	"eggs":                                Nature,
	"Xbox 360 (Video Game Platform)":      Gaming,
	"RPG":                                 Gaming,
	"design":                              Art,
	"market":                              Economics,
	"cars":                                Automotive,
	"fruits":                              Food,
	"flowers":                             Nature,
	"ram":                                 Technology,
	"lessons":                             Learning,
	"token free":                          Blockchain,
	"vegán":                               Food,
	"Game":                                Gaming,
	"investing":                           Economics,
	"samsung":                             Technology,
	"racing":                              Sports,
	"online learning":                     Learning,
	"dollar":                              Economics,
	"software":                            Technology,
	"beach":                               Nature,
	"gta":                                 Gaming,
	"windows":                             Technology,
	"let’s play":                          Gaming,
	"Minecraft":                           Gaming,
	"race":                                Automotive,
	"skyrim":                              Gaming,
	"rainbow":                             Nature,
	"health":                              Fitness,
	"Action-adventure Game (Media Genre)": Gaming,
	"programming":                         Technology,
	"sony interactive entertainment":      Gaming,
	"dlc":                                 Gaming,
	"diy":                                 Learning,
	"bitcoin price":                       Blockchain,
	"monetary reform":                     Economics,
	"xbox360":                             Gaming,
	"zelda":                               Gaming,
	"Steam":                               Gaming,
	"capcom":                              Gaming,
	"economic":                            Economics,
	"simulation":                          Technology,
	"recession":                           Economics,
	"fortnite battle royale":              Gaming,
	"altcoins":                            Blockchain,
	"facebook":                            Technology,
	"cryptocurrency news":                 Blockchain,
	"singleplayer":                        Gaming,
	"altcoin":                             Blockchain,
	"pacman":                              Gaming,
	"fashion":                             Art,
	"gta 5":                               Gaming,
	"Grand Theft Auto V":                  Gaming,
	"valve":                               Gaming,
	"Massively Multiplayer Online Role-playing Game (Video Game Genre)": Gaming,
	"#gaming":                               Gaming,
	"Bmw":                                   Automotive,
	"halo":                                  Gaming,
	"Hillary Clinton":                       News,
	"trading":                               Economics,
	"computer games":                        Gaming,
	"vehicle":                               Automotive,
	"desktop":                               Technology,
	"coin":                                  Blockchain,
	"water":                                 Nature,
	"nintendo switch":                       Gaming,
	"progressive talk":                      News,
	"3d games":                              Gaming,
	"animals":                               Nature,
	"install":                               Technology,
	"MOBA":                                  Gaming,
	"Ps2":                                   Gaming,
	"Role-playing Video Game (Media Genre)": Gaming,
	"trump":                                 News,
	"ripple":                                Blockchain,
	"parody":                                Funny,
	"supercell":                             Gaming,
	"dota2":                                 Gaming,
	"microsoft":                             Technology,
	"sims":                                  Gaming,
	"barack obama":                          News,
	"funny video":                           Funny,
	"finance":                               Economics,
	"floral":                                Nature,
	"creative hairstyles":                   Art,
	"food holidays":                         Food,
	"colorful hair":                         Art,
	"currency":                              Economics,
	"free bitcoin":                          Blockchain,
	"how-to":                                Learning,
	"pc gaming":                             Gaming,
	"Playstation 4":                         Gaming,
	"twitter":                               Technology,
	"battle royale":                         Gaming,
	"rpg games":                             Gaming,
	"sims 4":                                Gaming,
	"Android":                               Technology,
	"Benz":                                  Automotive,
	"silly":                                 Funny,
	"roblox":                                Gaming,
	"Mw3":                                   Gaming,
	"humour":                                Funny,
	"far cry 5":                             Gaming,
	"Mobile":                                Technology,
	"squad gameplay":                        Gaming,
	"tf2":                                   Gaming,
	"Auto Show (Event)":                     Automotive,
	"business":                              Economics,
	"apple":                                 Technology,
	"Ps3":                                   Gaming,
	"Resident Evil":                         Gaming,
	"iOS":                                   Technology,
	"Mercedes":                              Automotive,
	"engine":                                Automotive,
	"indie game":                            Gaming,
	"overwatch":                             Gaming,
	"brawl":                                 Gaming,
	"ltc":                                   Blockchain,
	"Call of Duty®: Black Ops III":          Gaming,
	"Donald Trump":                          News,
	"dash":                                  Blockchain,
	"newscast":                              News,
	"server":                                Technology,
	"gardening":                             Nature,
	"console":                               Gaming,
	"mugen":                                 Gaming,
	"Play":                                  Gaming,
	"Nvidia":                                Technology,
	"cool long hair":                        Art,
	"howto":                                 Learning,
	"Mass effect":                           Gaming,
	"mercedes":                              Automotive,
	"ubisoft":                               Gaming,
	"open source":                           Technology,
	"Minecraft: PlayStation®4 Edition":      Gaming,
	"rts":                                   Gaming,
	"mmorpg":                                Gaming,
	"first person shooter":                  Gaming,
	"eos":                                   Blockchain,
	"motorcycle":                            Automotive,
	"Action Role-playing Game (Video Game Genre)": Gaming,
	"steemit":                        Blockchain,
	"porsche":                        Automotive,
	"sport":                          Sports,
	"training":                       Sports,
	"Apple":                          Technology,
	"coinbase":                       Blockchain,
	"Role-playing Game (Game Genre)": Gaming,
	"sonic":                          Gaming,
	"advice":                         Learning,
	"videogames":                     Gaming,
	"Simulator":                      Gaming,
	"level":                          Gaming,
	"apps":                           Technology,
	"sims 3":                         Gaming,
	"Satire":                         Funny,
	"esports":                        Gaming,
	"Minecraft (Video Game)":         Gaming,
	"simulator":                      Gaming,
	"horrible gamers":                Gaming,
	"Bus":                            Automotive,
	"moba":                           Gaming,
	"football":                       Sports,
	"cryptocurrencies":               Blockchain,
	"the game":                       Gaming,
	"laptop":                         Technology,
	"link":                           Gaming,
	"Game Reviews":                   Gaming,
	"sims 5":                         Gaming,
	"snk":                            Gaming,
	"online games":                   Gaming,
	"squad game":                     Gaming,
	"switch":                         Gaming,
	"Lets Play":                      Gaming,
	"racism":                         News,
	"jeep":                           Automotive,
}
