version: "3"

services:
  #############
  ## Lbrycrd ##
  #############
  lbrycrd:
    image: lbry/lbrycrd:v0.12.4.1
    restart: always
    ports:
      - "15201:29246"
      - "15200:29245"
    ## host volumes for persistent data such as wallet private keys.
    volumes:
      - "./persist:/data"
    environment:
      - RUN_MODE=regtest
  ###################
  ## Wallet Server ##
  ###################
  walletserver:
    image: lbry/wallet-server:v0.38.5
    restart: always
    volumes:
      - "./persist/.walletserver/database:/database"
    environment:
      - DB_DIRECTORY=/database
      - MAX_SEND=1000000000000000000000
      - DAEMON_URL=http://lbry:lbry@lbrycrd:29245/
      - MAX_SUBS=1000000000000
      - BANDWIDTH_LIMIT=80000000000
      - SESSION_TIMEOUT=10000000000000000000000000
      - TCP_PORT=50001
    ports:
      - "15300:50001"
    ulimits:
      nofile: 90000
    #    command: lbry.wallet.server.coin.LBC
    command: lbry.wallet.server.coin.LBCRegTest
  #############
  ## Lbrynet ##
  #############
  lbrynet:
    image: lbry/lbrynet:v0.38.5
    restart: "no"
    ports:
      - "15100:5279"
      - "15101:5280"
    environment:
      - LBRY_STREAMING_SERVER=0.0.0.0:5280
    volumes:
      - "./persist/.lbrynet:/home/lbrynet"
      - ".:/etc/lbry" #Put your daemon_settings.yml here
      # /private/var/tmp for OSX and /var/tmp for Linux
      - "/private/var/tmp:/var/tmp"
